# Generated by Django 2.2.20 on 2024-01-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='お名前')),
                ('email', models.EmailField(max_length=50, verbose_name='メールアドレス')),
                ('title', models.BooleanField(choices=[(1, '商品について'), (2, 'お届けについて'), (3, '商品返品について'), (4, 'その他')], default=0, verbose_name='お問合せ項目')),
                ('message', models.TextField(max_length=400, verbose_name='お問合せ内容')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
