# Generated by Django 2.2.20 on 2024-01-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='create_date',
        ),
    ]
