# Generated by Django 2.2.20 on 2024-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240103_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='対応ステイタス'),
        ),
    ]
