# Generated by Django 2.2.20 on 2024-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.BooleanField(choices=[('-----------', '-----------'), ('商品について', '商品について'), ('お届けについて', 'お届けについて'), ('商品返品について', '商品返品について'), ('その他', 'その他')], default='-----------', verbose_name='お問合せ項目'),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
