# Generated by Django 2.2.20 on 2024-01-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20240103_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('-----------', '-----------'), ('商品について', '商品について'), ('お届けについて', 'お届けについて'), ('商品返品について', '商品返品について'), ('その他', 'その他')], default='-----------', max_length=20, verbose_name='お問合せ項目'),
        ),
    ]
