# Generated by Django 2.2.20 on 2024-01-05 20:04

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20240103_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, validators=[pages.models.validate_fullwidth], verbose_name='お名前'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='対応ステータス'),
        ),
    ]
