# Generated by Django 2.2.20 on 2023-11-25 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=20, verbose_name='パスワード')),
                ('username', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('kana', models.CharField(max_length=50, verbose_name='フリガナ')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
            ],
        ),
    ]
