# Generated by Django 2.2.20 on 2023-12-17 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231216_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='include_invoince',
            new_name='include_invoice',
        ),
        migrations.AddField(
            model_name='destination',
            name='kana',
            field=models.CharField(blank=True, max_length=200, verbose_name='フリガナ'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
