# Generated by Django 2.2.20 on 2023-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231217_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='お届け日'),
        ),
    ]
