# Generated by Django 2.2.20 on 2023-12-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231217_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='kana',
            field=models.CharField(max_length=200, verbose_name='フリガナ'),
        ),
    ]
