# Generated by Django 2.2.20 on 2023-12-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231226_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, '注文受付'), (2, '配達済み'), (3, 'キャンセル済み')], default=1, max_length=200, null=True, verbose_name='注文ステータス'),
        ),
    ]
