# Generated by Django 2.2.20 on 2023-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231217_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='要望'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=200, verbose_name='注文ステータス'),
        ),
    ]
