# Generated by Django 2.2.20 on 2023-12-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20231231_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', '注文受付'), ('delivered', '配達済み'), ('canceled', 'キャンセル済み')], default='accepted', max_length=200, null=True, verbose_name='注文ステータス'),
        ),
    ]
