# Generated by Django 2.2.20 on 2024-01-06 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20231231_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('female', '女性'), ('male', '男性'), ('not_specified', '未回答')], max_length=20, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kana',
            field=models.CharField(max_length=50, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='お名前'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='正しい郵便番号を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefecture',
            field=models.CharField(max_length=50, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='プライバシーポリシーに同意'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(max_length=100, null=True, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='正しい電話番号を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='正しい郵便番号を入力してください。', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tel_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='正しい電話番号を入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
