# Generated by Django 2.2.20 on 2024-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240104_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='プライバシーポリシーに同意'),
        ),
    ]
