# Generated by Django 2.2.20 on 2024-01-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240104_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy_policy_agreement',
            field=models.BooleanField(blank=True, default=False, verbose_name='プライバシーポリシーに同意'),
        ),
    ]
