# Generated by Django 2.2.20 on 2024-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240105_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='プライバシーポリシーに同意'),
        ),
    ]
