# Generated by Django 2.2.20 on 2023-01-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.CharField(max_length=1000, verbose_name='節名')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='画像')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('stock', models.PositiveIntegerField(verbose_name='在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Category', verbose_name='カテゴリー')),
            ],
        ),
    ]
