# Generated by Django 2.2.20 on 2023-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20230123_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像2'),
        ),
    ]
