# Generated by Django 2.2.20 on 2023-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20231130_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ManyToManyField(related_name='items', to='items.Image'),
        ),
        migrations.DeleteModel(
            name='Item_image',
        ),
    ]
