# Generated by Django 2.2.20 on 2023-11-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20231130_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='items.Image'),
        ),
    ]
