# Generated by Django 2.2.20 on 2023-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20231130_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='test', max_length=200, verbose_name='画像名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='items.Image'),
        ),
    ]
