# Generated by Django 2.2.20 on 2023-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20231130_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='second_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.ManyToManyField(blank=True, related_name='item', to='items.Image'),
        ),
    ]
