# Generated by Django 2.2.20 on 2023-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20231205_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='購入数'),
        ),
    ]
