# Generated by Django 2.2.20 on 2023-12-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20231206_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
