# Generated by Django 2.2.20 on 2023-12-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20231206_2217'),
        ('items', '0009_auto_20231202_2246'),
    ]

    operations = [
    ]
