# Generated by Django 2.2.20 on 2023-12-15 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0012_merge_20231207_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='クーポンコード')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='割引率')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('tel_number', models.CharField(max_length=11, verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, verbose_name='お届け日')),
                ('gift_wrapping', models.BooleanField(default=False, verbose_name='ギフトラッピング')),
                ('requrest_comment', models.CharField(max_length=1000, verbose_name='要望')),
                ('include_invoince', models.BooleanField(default=True, verbose_name='レシート同封')),
                ('status', models.CharField(max_length=200, verbose_name='注文ステータス')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Coupon')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='購入数')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='購入価格')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Order')),
            ],
        ),
    ]
