# Generated by Django 2.2.20 on 2023-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20231228_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='おすすめ'),
        ),
    ]
