# Generated by Django 2.2.20 on 2023-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20231228_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_percent',
            field=models.PositiveIntegerField(choices=[(8, 8), (10, 10)], default=8, null=True, verbose_name='消費税'),
        ),
    ]
