# Generated by Django 2.2.20 on 2023-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_item_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_percent',
            field=models.PositiveIntegerField(choices=[(8, 8), (10, 10)], default=8, null=True, verbose_name='消費税'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=None, null=True, verbose_name='おすすめ'),
        ),
    ]
