# Generated by Django 2.2.20 on 2023-12-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20231228_1729'),
        ('items', '0021_auto_20231230_0006'),
    ]

    operations = [
    ]
