# Generated by Django 2.2.20 on 2023-12-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20231231_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='liked_users',
        ),
    ]
