# Generated by Django 2.2.20 on 2024-01-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_remove_item_liked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='クーポンコード')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='割引率')),
                ('deleted', models.BooleanField(default=False, verbose_name='削除ステイタス')),
                ('description', models.CharField(max_length=1000, verbose_name='クーポン詳細')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=False, null=True, verbose_name='おすすめ'),
        ),
    ]
